plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/quang/mshelse-server/mshelse/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/home/quang/mshelse-server/mshelse"
command = "expo export -p web"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]